<?php

/**
 * @see CheckValues
 * 
 *  A classe ...
 */

namespace App\Libraries\Tools;

class Treatment
{

    public function __construct()
    {
        /**
         * @see No momento em que estou instanciando a classe, preciso criar modelos de token para manipular ao longo do projeto.
         */
     
    }
    public function clean_field($field){

		if(!empty($field)){
	
			return  htmlspecialchars($field);
		}else{
			return null;
		}
	}
	
	public function filter_field($field, $key){
		
		if(!empty($field) && strstr($field, $key) == true){
			echo "checked";
		}
	}
	
	public function search_field($field, $key){

		if(!empty($field) && strstr($field, $key) == true){
			$list = explode(";",$field);
			foreach($list as $value){
				if($value == $key){
					echo $value;
				}
			}
		}
	}
	
	public function filter_field_select($field, $key){

		if(!empty($field) && strstr($field, $key) == true){
			echo "selected";
		}
	}
	
	public function test_archive($archive, $id){
	 
		if ( $archive && !isset( $archive['error'] ) ) {
			echo "File is valid, and was successfully uploaded.\n";
			
		} else {
			/**
			 * Error generated by _wp_handle_upload()
			 * @see _wp_handle_upload() in wp-admin/includes/file.php
			 */
			echo $$archive['error'];
			exit();
		}
	}
}
